name: front-production-deploy

on:
  pull_request:
    branches: main

jobs:
  build:
    name: Build, Deploy to S3 bucket
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    strategy:
      matrix:
        node-version: [16.x]
    env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_DISTRIBUTION_ID: ${{ secrets.AWS_DISTRIBUTION_ID }}
        SOURCE_DIR: 'build'
        REACT_APP_INTRA: ${{ secrets.REACT_APP_INTRA }}
        REACT_APP_HOME: ${{ secrets.REACT_APP_HOME }}
        REACT_APP_BACKEND_ENDPOINT_URL: ${{ secrets.REACT_APP_BACKEND_ENDPOINT_URL }}
        REACT_APP_REGISTER_URL: ${{ secrets.REACT_APP_REGISTER_URL }}
        REACT_APP_MESSAGE_REDIRECT_URL: ${{ secrets.REACT_APP_MESSAGE_REDIRECT_URL }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2 # 워크플로에서 액세스할 수 있도록 에서 저장소를 체크아웃
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        uses: actions/cache@v2
        env: 
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install Dependencies
        if: steps.cache_dependencies.outputs.cache-hit == ''
        run: yarn

      - name: Build
        run: yarn build

      - name: Transfer to S3 for serving static
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete

      - name: CloudFront Invalidity
        uses: chetan/invalidate-cloudfront-action@master
        env:
          DISTRIBUTION: ${{ secrets.AWS_DISTRIBUTION_ID }}
          PATHS: '/*'
        continue-on-error: true
